terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  region = "us-central-1"
  access_key = "AKIAZWIJSY4UI7XUBJNH"
  secret_key = "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"
}



# TERRAFORM {
#   REQUIRED_PROVIDERS {
#     AWS = {
#       SOURCE  = "HASHICORP/AWS"
#       VERSION = "3.22"
#     }
#     FORTIOS = {
#       SOURCE  = "FORTINETDEV/FORTIOS"
#       VERSION = "1.7"
#     }
#   }

#   BACKEND "S3" {

#     BUCKET = "TRAD-NONPROD-NES-MANAGEMENT"
#     KEY    = "ENR-FR-INFRASTRUCTURE/DEV/TERRAFORM.TFSTATE"
#     REGION = "EU-CENTRAL-1"

#     PROFILE = "TRAD-NONPROD-NES-TOOLS"
#   }
# }

# # CONFIGURE THE AWS PROVIDER FOR INDUSTRIAL EDGE ACCOUNT
# PROVIDER "AWS" {
#   ALIAS = "INDUSTRIAL_SHARED"
#   REGION = "EU-CENTRAL-1"

#   ALLOWED_ACCOUNT_IDS = ["646918904450"]
#   PROFILE = "TRAD-NONPROD-NES-TOOLS"
# }

# PROVIDER "AWS" {
#   ALIAS = "ENR"
#   REGION = "EU-CENTRAL-1"

#   ALLOWED_ACCOUNT_IDS = ["290221653127"]
#   PROFILE = "TRAD-NONPROD-ENR-FR"
# }

# PROVIDER "AWS" {
#   ALIAS = "ENTERPRISE_TRANSIT"
#   REGION = "EU-CENTRAL-1"

#   ALLOWED_ACCOUNT_IDS = ["209361602550"]
#   PROFILE = "TRAD-EDGE-SERVICES"
# }

# DATA "TERRAFORM_REMOTE_STATE" "SHARED_EDGE" {
#   BACKEND = "S3"
#   CONFIG = {
#     BUCKET  = "TRAD-PROD-SHARED-MANAGEMENT"
#     KEY     = "SHARED-EDGE/DEV/TERRAFORM.TFSTATE"
#     REGION  = "EU-CENTRAL-1"
#     PROFILE = "TRAD-SHARED-SERVICES"
#   }
# }
